Add project info to web UI
NatLibFi/Annif pull request #654
Opened 2022-12-08 10:57 UTC by UnniKohonen

This PR adds information about a selected project to the web UI.

A button is added under the project selection:
![Screenshot 2022-12-08 at 11-43-39 Annif](https://user-images.githubusercontent.com/45235116/206415341-05170f62-7948-41cf-8a82-db65a95ef4ba.png)

This opens a box with the information on the project:
![Screenshot 2022-12-08 at 11-43-48 Annif](https://user-images.githubusercontent.com/45235116/206415532-ff3f2efd-1bb3-4c82-90f3-25fde46600fc.png)

IMO a version with the info in a popup next to the project selection would look cleaner but I'm not sure how to implement it yet.

2022-12-14 14:39 UTC, osma commented
Great work so far!

I think the visual design could be a bit simpler instead of a big button. How about making it similar to the collapsible details/summary view available here on GitHub, something like this (try clicking):

<details>
<summary>Project information</summary>
Project ID: yso-fi<br/>
Language: fi<br/>
Backend type: nn_ensemble<br/>
Trained: yes<br/>
Last modified: 2022-11-21 15:07:57 UTC
</details>

Here is a rough sketch how it could look (sorry for the bad alignment, not intended!)

![kuva](https://user-images.githubusercontent.com/1132830/207624780-f484e8c0-2743-4175-a0bd-6a765aa6a5e4.png)

It would be closed by default of course.

2022-12-16 09:18 UTC, UnniKohonen commented
I changed it to this now:
![Screenshot 2022-12-16 at 10-45-02 Annif](https://user-images.githubusercontent.com/45235116/208059721-529b9ca3-71e3-4d68-8508-c4a8762f50a0.png)
![Screenshot 2022-12-16 at 10-44-36 Annif](https://user-images.githubusercontent.com/45235116/208059707-de241be4-84fc-4add-a910-24a9a7f51706.png)

I left the animation for the collapse element on but it can be removed too if it's distracting.

2022-12-21 08:24 UTC, osma requested changes
This is excellent! I think the animation is also OK.

A couple of very minor visual details that you could perhaps address:

1. "Project information" is now set in bold - I think it could be just regular text. Now it stands out more than necessary, because there is no other bold text on the page.
2. Is there any chance to left-align the text column so that "Project information" and "Project ID" would be aligned?

Other than these two minor details, I think this is good for merging!

2022-12-21 10:04 UTC, osma approved these changes

2022-12-21 10:37 UTC, merged

2023-01-02 10:54 UTC, juhoinkinen commented
We should remember to update [the Wiki page for the Web UI](https://github.com/NatLibFi/Annif/wiki/Web-user-interface) when the next release is made, it is quite old already.